# Chapter 2 Exercises
## Table of Contents
1. [Setting up the environment](#setting-up-the-environment)

## Setting up the environment
- By using **np.random.seed(0)**, I ensure that the random values generated will be the same every time I run the code. This is important for reproducibility.
- The function **np.random.randn(10, 3)** generates a $[10\times3]$ matrix filled with random numbers sampled from the standard normal distribution ($\mu=0$ and $\sigma=1$). This matrix represents $3$ features, each containing $10$ samples.
- Printing the matrix helps inspect the input data before using it in further computation or visualization.

In [4]:
# Import packages
import numpy as np
import matplotlib.pyplot as plt

# Reproducibility of random values
np.random.seed(0)

# Generate some random input data (10 samples, 3 features)
input_data = np.random.randn(10, 3)
print('Input data:')
print(input_data)

Input data:
[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]
 [ 0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826]
 [ 0.3130677  -0.85409574 -2.55298982]
 [ 0.6536186   0.8644362  -0.74216502]
 [ 2.26975462 -1.45436567  0.04575852]
 [-0.18718385  1.53277921  1.46935877]]


## Define Neural Network Layers
- The **weight (w) matrix** and the **bias (b) vector** are defined and will be used for a simple transformation of the ```input_data```. This simulates a linear layer of a Neural Network.
- Using ```np.random.randn(3, 2)```, corresponding to $3$ **features** of the ```input units``` and $2$ ```output units```.
- The **bias vector** is also initialized randomly with 2 values, representing the biases for the two output units.
- Printing both the **weights** and **biases**, show the initialized values before deploying them.

In [7]:
# Define weight matrix (3 features, 2 outputs)
weight = np.random.randn(3, 2)

# Define bias vector
biases = np.random.randn(2)

print('\nWeight:')
print(weight)
print('\nBiases:')
print(biases)


Weight:
[[-1.25279536  0.77749036]
 [-1.61389785 -0.21274028]
 [-0.89546656  0.3869025 ]]

Biases:
[-0.51080514 -1.18063218]


## Perform the forward pass
- Perform a forward pass through a simple linear layer
- The basic **equation** for the neural network is $$y = wx + b$$ where $y$ = output, $w$ = weight matrix, $x$ = input data/feature, and $b$ = bias vector.
- The $wx$ is computed by performing **dot product** using ```np.dot()```. This transforms the matrix-vector data into a $2$ output units.
- The biases ($b$) is added to the dot product.

In [16]:
# Check the shape of the weight matrix and input_data
print('\nWeight_Shape: ', weight.shape)
print('Input_data_Shape: ', input_data.shape)

# Perform the forward pass
output_data = np.dot(input_data, weight) + biases
print('\nOutput_data:')
print(output_data)


Weight_Shape:  (3, 2)
Input_data_Shape:  (10, 3)

Output_data:
[[-4.24304173  0.48444812]
 [-5.4571139  -0.2137754 ]
 [-1.3643674  -0.44968346]
 [-2.55992594 -0.32937763]
 [-2.0580654  -0.44308608]
 [-3.15640942 -1.31843066]
 [ 2.76152538 -1.74328264]
 [-2.06018324 -1.14349593]
 [-1.04812079  0.91118639]
 [-4.0658128  -1.08375112]]
