## Chapter 2 Exercises
### Table of Contents
1. [Setting up the environment](#setting-up-the-environment)

### Setting up the environment
- By using **np.random.seed(0)**, I ensure that the random values generated will be the same every time I run the code. This is important for reproducibility.
- The function **np.random.randn(10, 3)** generates a $[10\times3]$ matrix filled with random numbers sampled from the standard normal distribution ($\mu=0$ and $\sigma=1$). This matrix represents $3$ features, each containing $10$ samples.
- Printing the matrix helps inspect the input data before using it in further computation or visualization.

In [1]:
# Import packages
import numpy as np
import matplotlib.pyplot as plt

# Reproducibility of random values
np.random.seed(0)

# Generate some random input data (10 samples, 3 features)
input_data = np.random.randn(10, 3)
print('Input data:')
print(input_data)

Input data:
[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]
 [ 0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826]
 [ 0.3130677  -0.85409574 -2.55298982]
 [ 0.6536186   0.8644362  -0.74216502]
 [ 2.26975462 -1.45436567  0.04575852]
 [-0.18718385  1.53277921  1.46935877]]
